// Generated by opencode with deepseek-v4-flash-free
#include "ast.hxx"

#include <catch2/catch_test_macros.hpp>

using namespace basic;

// --- Node ---

TEST_CASE("Node default constructor", "[ast]")
{
    Node n;
    CHECK(n.kind == NodeKind::Empty);
    CHECK(n.line == 0);
}

TEST_CASE("Node parameterized constructor", "[ast]")
{
    Node n{NodeKind::Program, 42};
    CHECK(n.kind == NodeKind::Program);
    CHECK(n.line == 42);
}

TEST_CASE("Node id is auto-incremented", "[ast]")
{
    Node a{NodeKind::Number, 1};
    Node b{NodeKind::Text, 2};
    Node c{NodeKind::Variable, 3};
    CHECK(b.id() == a.id() + 1);
    CHECK(c.id() == b.id() + 1);
}

TEST_CASE("Node::Ptr typedef", "[ast]")
{
    Node::Ptr ptr = std::make_shared<Node>(NodeKind::Empty, 5);
    CHECK(ptr->kind == NodeKind::Empty);
    CHECK(ptr->line == 5);
}

// --- node() helper ---

TEST_CASE("node helper creates shared_ptr", "[ast]")
{
    auto n = node<Number>(3.14, 1);
    CHECK(n->kind == NodeKind::Number);
    CHECK(n->_value == 3.14);
}

// --- Expression ---

TEST_CASE("Expression base class", "[ast]")
{
    Expression e{NodeKind::Binary, 5};
    CHECK(e.kind == NodeKind::Binary);
    CHECK(e.line == 5);
}

TEST_CASE("Expression::Ptr typedef", "[ast]")
{
    Expression::Ptr ptr = std::make_shared<Number>(1.0, 1);
    CHECK(ptr->kind == NodeKind::Number);
}

// --- Boolean ---

TEST_CASE("Boolean node true", "[ast]")
{
    Boolean b{true, 3};
    CHECK(b.kind == NodeKind::Boolean);
    CHECK(b.line == 3);
    CHECK(b._value == true);
}

TEST_CASE("Boolean node false", "[ast]")
{
    Boolean b{false, 4};
    CHECK(b.kind == NodeKind::Boolean);
    CHECK(b._value == false);
}

// --- Number ---

TEST_CASE("Number node", "[ast]")
{
    Number n{2.718, 5};
    CHECK(n.kind == NodeKind::Number);
    CHECK(n.line == 5);
    CHECK(n._value == 2.718);
}

TEST_CASE("Number node zero", "[ast]")
{
    Number n{0.0, 1};
    CHECK(n._value == 0.0);
}

// --- Text ---

TEST_CASE("Text node", "[ast]")
{
    Text t{"hello", 2};
    CHECK(t.kind == NodeKind::Text);
    CHECK(t.line == 2);
    CHECK(t._value == "hello");
}

TEST_CASE("Text node empty string", "[ast]")
{
    Text t{"", 1};
    CHECK(t._value == "");
}

// --- Variable ---

TEST_CASE("Variable node", "[ast]")
{
    Variable v{"x", 3};
    CHECK(v.kind == NodeKind::Variable);
    CHECK(v.line == 3);
    CHECK(v._name == "x");
}

// --- Operation enum ---

TEST_CASE("Operation values", "[ast]")
{
    CHECK(static_cast<int>(Operation::None) == 0);
    CHECK(Operation::Add != Operation::Sub);
}

// --- Unary ---

TEST_CASE("Unary node", "[ast]")
{
    auto operand = node<Number>(5.0, 1);
    Unary u{Operation::Not, operand, 2};
    CHECK(u.kind == NodeKind::Unary);
    CHECK(u.line == 2);
    CHECK(u._operation == Operation::Not);
    CHECK(u._operand->kind == NodeKind::Number);
}

// --- Binary ---

TEST_CASE("Binary node", "[ast]")
{
    auto left = node<Number>(1.0, 1);
    auto right = node<Number>(2.0, 2);
    Binary b{Operation::Add, left, right, 3};
    CHECK(b.kind == NodeKind::Binary);
    CHECK(b._operation == Operation::Add);
    auto l = std::static_pointer_cast<Number>(b._left);
    CHECK(l->_value == 1.0);
    auto r = std::static_pointer_cast<Number>(b._right);
    CHECK(r->_value == 2.0);
}

// --- Apply ---

TEST_CASE("Apply node with no arguments", "[ast]")
{
    Apply a{"SIN", {}, 1};
    CHECK(a.kind == NodeKind::Apply);
    CHECK(a._callee == "SIN");
    CHECK(a._arguments.empty());
}

TEST_CASE("Apply node with arguments", "[ast]")
{
    auto arg = node<Number>(3.14, 1);
    Apply a{"MID", {arg, node<Number>(1.0, 2)}, 3};
    CHECK(a._callee == "MID");
    CHECK(a._arguments.size() == 2);
}

// --- Array ---

TEST_CASE("Array node empty", "[ast]")
{
    Array a{{}, 1};
    CHECK(a.kind == NodeKind::Array);
    CHECK(a._elements.empty());
}

TEST_CASE("Array node with elements", "[ast]")
{
    Array a{{node<Number>(1.0, 1), node<Number>(2.0, 2)}, 3};
    CHECK(a._elements.size() == 2);
}

// --- Statement ---

TEST_CASE("Statement base class", "[ast]")
{
    Statement s{NodeKind::Print, 7};
    CHECK(s.kind == NodeKind::Print);
    CHECK(s.line == 7);
}

TEST_CASE("Statement::Ptr typedef", "[ast]")
{
    Statement::Ptr ptr = std::make_shared<Print>(node<Number>(0.0, 1), 1);
    CHECK(ptr->kind == NodeKind::Print);
}

// --- Sequence ---

TEST_CASE("Sequence node", "[ast]")
{
    std::vector<Statement::Ptr> items;
    items.push_back(std::make_shared<Print>(node<Number>(1.0, 1), 1));
    Sequence seq{std::move(items), 2};
    CHECK(seq.kind == NodeKind::Sequence);
    CHECK(seq._items.size() == 1);
}

// --- Dim ---

TEST_CASE("Dim node", "[ast]")
{
    auto size = node<Number>(10.0, 1);
    Dim d{"arr", size, 2};
    CHECK(d.kind == NodeKind::Dim);
    CHECK(d._name == "arr");
    CHECK(d._size->kind == NodeKind::Number);
}

// --- Input ---

TEST_CASE("Input node", "[ast]")
{
    auto var = std::make_shared<Variable>("n", 1);
    Input inp{var, 2};
    CHECK(inp.kind == NodeKind::Input);
    CHECK(inp._variable->_name == "n");
}

// --- Print ---

TEST_CASE("Print node", "[ast]")
{
    auto expr = node<Text>("hello", 1);
    Print p{expr, 2};
    CHECK(p.kind == NodeKind::Print);
    CHECK(p._expr->kind == NodeKind::Text);
}

// --- Let ---

TEST_CASE("Let node", "[ast]")
{
    auto var = std::make_shared<Variable>("x", 1);
    auto expr = node<Number>(42.0, 2);
    Let l{var, expr, 3};
    CHECK(l.kind == NodeKind::Let);
    CHECK(l._variable->_name == "x");
    CHECK(l._expr->kind == NodeKind::Number);
}

// --- If ---

TEST_CASE("If node without else", "[ast]")
{
    auto cond = node<Boolean>(true, 1);
    auto decision = std::make_shared<Print>(node<Text>("yes", 2), 2);
    If i{cond, decision, nullptr, 3};
    CHECK(i.kind == NodeKind::If);
    CHECK(i._condition->kind == NodeKind::Boolean);
    CHECK(i._decision->kind == NodeKind::Print);
    CHECK(i._alternative == nullptr);
}

TEST_CASE("If node with else", "[ast]")
{
    auto cond = node<Boolean>(false, 1);
    auto decision = std::make_shared<Print>(node<Text>("then", 2), 2);
    auto alt = std::make_shared<Print>(node<Text>("else", 3), 3);
    If i{cond, decision, alt, 4};
    CHECK(i._alternative->kind == NodeKind::Print);
}

// --- While ---

TEST_CASE("While node", "[ast]")
{
    auto cond = node<Boolean>(true, 1);
    auto body = std::make_shared<Print>(node<Number>(0.0, 2), 2);
    While w{cond, body, 3};
    CHECK(w.kind == NodeKind::While);
    CHECK(w._condition->kind == NodeKind::Boolean);
    CHECK(w._body->kind == NodeKind::Print);
}

// --- For ---

TEST_CASE("For node", "[ast]")
{
    auto param = std::make_shared<Variable>("i", 1);
    auto begin = node<Number>(0.0, 2);
    auto end = node<Number>(10.0, 3);
    auto step = node<Number>(2.0, 4);
    auto body = std::make_shared<Print>(node<Number>(0.0, 5), 5);
    For f{param, begin, end, step, body, 6};
    CHECK(f.kind == NodeKind::For);
    CHECK(f._parameter->_name == "i");
    CHECK(f._begin->kind == NodeKind::Number);
    CHECK(f._end->kind == NodeKind::Number);
    CHECK(f._step->_value == 2.0);
    CHECK(f._body->kind == NodeKind::Print);
}

// --- Call ---

TEST_CASE("Call node", "[ast]")
{
    Call c{"PrintN", {node<Text>("hello", 1), node<Number>(3.0, 2)}, 3};
    CHECK(c.kind == NodeKind::Call);
    CHECK(c._subrCall->_callee == "PrintN");
    CHECK(c._subrCall->_arguments.size() == 2);
}

TEST_CASE("Call node with no arguments", "[ast]")
{
    Call c{"P0", {}, 1};
    CHECK(c._subrCall->_callee == "P0");
    CHECK(c._subrCall->_arguments.empty());
}

// --- Subroutine ---

TEST_CASE("Subroutine node", "[ast]")
{
    auto body = std::make_shared<Sequence>(std::vector<Statement::Ptr>{}, 2);
    Subroutine s{"Main", {"x", "y"}, body, 1};
    CHECK(s.kind == NodeKind::Subroutine);
    CHECK(s._name == "Main");
    CHECK(s._parameters.size() == 2);
    CHECK(s._parameters[0] == "x");
    CHECK(s._parameters[1] == "y");
}

TEST_CASE("Subroutine node with no parameters", "[ast]")
{
    auto body = std::make_shared<Sequence>(std::vector<Statement::Ptr>{}, 2);
    Subroutine s{"P0", {}, body, 1};
    CHECK(s._parameters.empty());
}

// --- Program ---

TEST_CASE("Program node", "[ast]")
{
    auto body = std::make_shared<Sequence>(std::vector<Statement::Ptr>{}, 2);
    auto sub = std::make_shared<Subroutine>("Main", std::vector<std::string>{}, body, 1);
    Program prog{"test.bas", {sub}, 0};
    CHECK(prog.kind == NodeKind::Program);
    CHECK(prog._filename == "test.bas");
    CHECK(prog._subroutines.size() == 1);
}

TEST_CASE("Program node with multiple subroutines", "[ast]")
{
    auto body = std::make_shared<Sequence>(std::vector<Statement::Ptr>{}, 2);
    auto s1 = std::make_shared<Subroutine>("A", std::vector<std::string>{}, body, 1);
    auto s2 = std::make_shared<Subroutine>("B", std::vector<std::string>{}, body, 2);
    Program prog{"multi.bas", {s1, s2}, 0};
    CHECK(prog._subroutines.size() == 2);
    CHECK(prog._subroutines[0]->_name == "A");
    CHECK(prog._subroutines[1]->_name == "B");
}

// --- NodeKind correspondence ---

TEST_CASE("NodeKind values match node types", "[ast]")
{
    CHECK(node<Boolean>(true, 1)->kind == NodeKind::Boolean);
    CHECK(node<Number>(0.0, 1)->kind == NodeKind::Number);
    CHECK(node<Text>("", 1)->kind == NodeKind::Text);
    CHECK(node<Variable>("", 1)->kind == NodeKind::Variable);

    auto dummy = node<Number>(0.0, 1);
    CHECK(node<Unary>(Operation::Not, dummy, 1)->kind == NodeKind::Unary);
    CHECK(node<Binary>(Operation::Add, dummy, dummy, 1)->kind == NodeKind::Binary);
    CHECK(node<Apply>("", std::vector<Expression::Ptr>{}, 1)->kind == NodeKind::Apply);
    CHECK(node<Array>(std::vector<Expression::Ptr>{}, 1)->kind == NodeKind::Array);
    CHECK(node<Sequence>(std::vector<Statement::Ptr>{}, 1)->kind == NodeKind::Sequence);
    CHECK(node<Dim>("", dummy, 1)->kind == NodeKind::Dim);
    CHECK(node<Input>(std::make_shared<Variable>("", 1), 1)->kind == NodeKind::Input);
    CHECK(node<Print>(dummy, 1)->kind == NodeKind::Print);
    CHECK(node<Let>(std::make_shared<Variable>("", 1), dummy, 1)->kind == NodeKind::Let);
    CHECK(node<If>(dummy, node<Print>(dummy, 1), nullptr, 1)->kind == NodeKind::If);
    CHECK(node<While>(dummy, node<Print>(dummy, 1), 1)->kind == NodeKind::While);

    auto v = std::make_shared<Variable>("i", 1);
    CHECK(node<For>(v, dummy, dummy, node<Number>(1.0, 1), node<Print>(dummy, 1), 1)->kind == NodeKind::For);
    CHECK(node<Call>("", std::vector<Expression::Ptr>{}, 1)->kind == NodeKind::Call);

    auto seq = node<Sequence>(std::vector<Statement::Ptr>{}, 1);
    CHECK(node<Subroutine>("", std::vector<std::string>{}, seq, 1)->kind == NodeKind::Subroutine);
    CHECK(node<Program>("", std::vector<Subroutine::Ptr>{}, 1)->kind == NodeKind::Program);
}

// --- dynamic_cast hierarchy ---

TEST_CASE("Dynamic casts between AST node types", "[ast]")
{
    Expression::Ptr expr = node<Number>(5.0, 1);
    CHECK(dynamic_cast<Number*>(expr.get()) != nullptr);
    CHECK(dynamic_cast<Expression*>(expr.get()) != nullptr);
    CHECK(dynamic_cast<Node*>(expr.get()) != nullptr);
    CHECK(dynamic_cast<Statement*>(expr.get()) == nullptr);

    Statement::Ptr stmt = std::make_shared<Print>(node<Number>(0.0, 1), 1);
    CHECK(dynamic_cast<Print*>(stmt.get()) != nullptr);
    CHECK(dynamic_cast<Statement*>(stmt.get()) != nullptr);
    CHECK(dynamic_cast<Node*>(stmt.get()) != nullptr);
    CHECK(dynamic_cast<Expression*>(stmt.get()) == nullptr);
}

TEST_CASE("Number can be cast through Expression to Node", "[ast]")
{
    auto num = node<Number>(1.0, 1);
    Node* asNode = num.get();
    CHECK(asNode->kind == NodeKind::Number);
}
