// Generated by opencode with deepseek-v4-flash-free
#include "lexeme.hxx"

#include <catch2/catch_test_macros.hpp>

using namespace basic;

TEST_CASE("Lexeme default constructor", "[lexeme]")
{
    Lexeme lex;
    CHECK(lex.kind == Token::None);
    CHECK(lex.value == "");
    CHECK(lex.line == 0);
}

TEST_CASE("Lexeme parameterized constructor", "[lexeme]")
{
    Lexeme lex{Token::Number, "42", 3};
    CHECK(lex.kind == Token::Number);
    CHECK(lex.value == "42");
    CHECK(lex.line == 3);
}

TEST_CASE("Lexeme parameterized constructor with text", "[lexeme]")
{
    Lexeme lex{Token::Text, "hello", 7};
    CHECK(lex.kind == Token::Text);
    CHECK(lex.value == "hello");
    CHECK(lex.line == 7);
}

TEST_CASE("Lexeme::is matches single token", "[lexeme]")
{
    Lexeme lex{Token::Subroutine, "SUB", 1};
    CHECK(lex.is(Token::Subroutine));
    CHECK_FALSE(lex.is(Token::Let));
}

TEST_CASE("Lexeme::is matches any of multiple tokens", "[lexeme]")
{
    Lexeme lex{Token::While, "WHILE", 1};
    CHECK(lex.is(Token::For, Token::While, Token::Let));
    CHECK_FALSE(lex.is(Token::If, Token::Let));
}

TEST_CASE("Lexeme::is matches with two tokens", "[lexeme]")
{
    Lexeme lex{Token::Eof, "EOF", 5};
    CHECK(lex.is(Token::None, Token::Eof));
}

TEST_CASE("Lexeme::is matches literal tokens", "[lexeme]")
{
    Lexeme num{Token::Number, "99", 1};
    CHECK(num.is(Token::Number, Token::True, Token::False));
    CHECK_FALSE(num.is(Token::Subroutine, Token::Dim));
}

TEST_CASE("Lexeme::is matches operator tokens", "[lexeme]")
{
    Lexeme op{Token::Add, "+", 1};
    CHECK(op.is(Token::Add, Token::Sub, Token::Mul));
}

TEST_CASE("Lexeme::is matches keyword tokens", "[lexeme]")
{
    Lexeme kw{Token::While, "WHILE", 1};
    CHECK(kw.is(Token::For, Token::While, Token::Let));
    CHECK_FALSE(kw.is(Token::If, Token::Call));
}

TEST_CASE("Lexeme::is with None token", "[lexeme]")
{
    Lexeme none;
    CHECK(none.is(Token::None));
}

TEST_CASE("Lexeme::toString format", "[lexeme]")
{
    Lexeme lex{Token::Number, "42", 3};
    CHECK(lex.toString() == "<Number, 42, 3>");
}

TEST_CASE("Lexeme::toString for text token", "[lexeme]")
{
    Lexeme lex{Token::Text, "hello", 1};
    CHECK(lex.toString() == "<Text, hello, 1>");
}

TEST_CASE("Lexeme::toString for identifier token", "[lexeme]")
{
    Lexeme lex{Token::Identifier, "Main", 2};
    CHECK(lex.toString() == "<IDENT, Main, 2>");
}

TEST_CASE("Lexeme::toString for default lexeme", "[lexeme]")
{
    Lexeme lex;
    CHECK(lex.toString() == "<None, , 0>");
}

TEST_CASE("toString for all Token values", "[lexeme]")
{
    CHECK(toString(Token::None) == "None");
    CHECK(toString(Token::Number) == "Number");
    CHECK(toString(Token::Text) == "Text");
    CHECK(toString(Token::True) == "TRUE");
    CHECK(toString(Token::False) == "FALSE");
    CHECK(toString(Token::Identifier) == "IDENT");
    CHECK(toString(Token::Subroutine) == "SUB");
    CHECK(toString(Token::Let) == "LET");
    CHECK(toString(Token::If) == "IF");
    CHECK(toString(Token::Then) == "THEN");
    CHECK(toString(Token::ElseIf) == "ELSEIF");
    CHECK(toString(Token::Else) == "ELSE");
    CHECK(toString(Token::While) == "WHILE");
    CHECK(toString(Token::For) == "FOR");
    CHECK(toString(Token::To) == "TO");
    CHECK(toString(Token::Step) == "STEP");
    CHECK(toString(Token::Call) == "CALL");
    CHECK(toString(Token::End) == "END");
    CHECK(toString(Token::NewLine) == "New Line");
    CHECK(toString(Token::Eq) == "=");
    CHECK(toString(Token::Ne) == "<>");
    CHECK(toString(Token::Lt) == "<");
    CHECK(toString(Token::Le) == "<=");
    CHECK(toString(Token::Gt) == ">");
    CHECK(toString(Token::Ge) == ">=");
    CHECK(toString(Token::LeftPar) == "(");
    CHECK(toString(Token::RightPar) == ")");
    CHECK(toString(Token::Comma) == ",");
    CHECK(toString(Token::Add) == "+");
    CHECK(toString(Token::Sub) == "-");
    CHECK(toString(Token::Amp) == "&");
    CHECK(toString(Token::Or) == "OR");
    CHECK(toString(Token::Mul) == "*");
    CHECK(toString(Token::Div) == "/");
    CHECK(toString(Token::Mod) == "MOD");
    CHECK(toString(Token::And) == "AND");
    CHECK(toString(Token::Pow) == "^");
    CHECK(toString(Token::Not) == "NOT");
    CHECK(toString(Token::Eof) == "Eof");
}
