// Generated by opencode with deepseek-v4-flash-free
#include "parser.hxx"
#include "ast.hxx"

#include <catch2/catch_test_macros.hpp>

#include <sstream>

using namespace basic;

static Program::Ptr parseStr(const std::string& input)
{
    auto stream = std::make_shared<std::istringstream>(input);
    Scanner scanner{*stream};
    Parser parser{scanner, "<test>"};
    return parser.parse();
}

static const Subroutine& onlySub(const Program& prog)
{
    REQUIRE(prog._subroutines.size() == 1);
    return *prog._subroutines[0];
}

static const Sequence& bodySeq(const Node& sub)
{
    auto seq = dynamic_cast<const Sequence*>(&sub);
    REQUIRE(seq != nullptr);
    return *seq;
}

// ---- Program ----

TEST_CASE("Parse empty input", "[parser]")
{
    auto prog = parseStr("");
    REQUIRE(prog != nullptr);
    CHECK(prog->_filename == "<test>");
    CHECK(prog->_subroutines.empty());
}

TEST_CASE("Parse whitespace-only input", "[parser]")
{
    auto prog = parseStr("   \t  ");
    REQUIRE(prog != nullptr);
    CHECK(prog->_subroutines.empty());
}

TEST_CASE("Parse newlines-only input", "[parser]")
{
    auto prog = parseStr("\n\n\n");
    REQUIRE(prog != nullptr);
    CHECK(prog->_subroutines.empty());
}

// ---- Subroutine ----

TEST_CASE("Parse subroutine with empty body", "[parser]")
{
    auto prog = parseStr("SUB Main\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    CHECK(sub._name == "Main");
    CHECK(sub._parameters.empty());
}

TEST_CASE("Parse empty parens subroutine", "[parser]")
{
    auto prog = parseStr("SUB Main()\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    CHECK(sub._name == "Main");
    CHECK(sub._parameters.empty());
}

TEST_CASE("Parse subroutine with one parameter", "[parser]")
{
    auto prog = parseStr("SUB f(x)\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    CHECK(sub._name == "f");
    REQUIRE(sub._parameters.size() == 1);
    CHECK(sub._parameters[0] == "x");
}

TEST_CASE("Parse subroutine with multiple parameters", "[parser]")
{
    auto prog = parseStr("SUB f(x, y, z)\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    REQUIRE(sub._parameters.size() == 3);
    CHECK(sub._parameters[0] == "x");
    CHECK(sub._parameters[1] == "y");
    CHECK(sub._parameters[2] == "z");
}

TEST_CASE("Parse multiple subroutines", "[parser]")
{
    auto prog = parseStr("SUB A\nEND SUB\nSUB B\nEND SUB\n");
    REQUIRE(prog != nullptr);
    REQUIRE(prog->_subroutines.size() == 2);
    CHECK(prog->_subroutines[0]->_name == "A");
    CHECK(prog->_subroutines[1]->_name == "B");
}

// ---- PRINT ----

TEST_CASE("Parse PRINT number", "[parser]")
{
    auto prog = parseStr("SUB Main\nPRINT 42\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    auto p = dynamic_cast<const Print*>(seq._items[0].get());
    REQUIRE(p != nullptr);
    auto n = dynamic_cast<const Number*>(p->_expr.get());
    REQUIRE(n != nullptr);
    CHECK(n->_value == 42.0);
}

TEST_CASE("Parse PRINT text", "[parser]")
{
    auto prog = parseStr("SUB Main\nPRINT \"Hello\"\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto p = dynamic_cast<const Print*>(seq._items[0].get());
    REQUIRE(p != nullptr);
    auto t = dynamic_cast<const Text*>(p->_expr.get());
    REQUIRE(t != nullptr);
    CHECK(t->_value == "Hello");
}

TEST_CASE("Parse PRINT variable", "[parser]")
{
    auto prog = parseStr("SUB Main\nPRINT x\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto p = dynamic_cast<const Print*>(seq._items[0].get());
    REQUIRE(p != nullptr);
    auto v = dynamic_cast<const Variable*>(p->_expr.get());
    REQUIRE(v != nullptr);
    CHECK(v->_name == "x");
}

// ---- LET ----

TEST_CASE("Parse LET number", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = 99\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    CHECK(l->_variable->_name == "x");
    auto n = dynamic_cast<const Number*>(l->_expr.get());
    REQUIRE(n != nullptr);
    CHECK(n->_value == 99.0);
}

TEST_CASE("Parse LET text", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = \"text\"\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto t = dynamic_cast<const Text*>(l->_expr.get());
    REQUIRE(t != nullptr);
    CHECK(t->_value == "text");
}

// ---- INPUT ----

TEST_CASE("Parse INPUT", "[parser]")
{
    auto prog = parseStr("SUB Main\nINPUT n\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    auto inp = dynamic_cast<const Input*>(seq._items[0].get());
    REQUIRE(inp != nullptr);
    CHECK(inp->_variable->_name == "n");
}

// ---- IF ----

TEST_CASE("Parse IF-THEN without else", "[parser]")
{
    auto prog = parseStr("SUB Main\nIF 1 THEN\nPRINT 0\nEND IF\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    auto i = dynamic_cast<const If*>(seq._items[0].get());
    REQUIRE(i != nullptr);
    auto cond = dynamic_cast<const Number*>(i->_condition.get());
    REQUIRE(cond != nullptr);
    CHECK(cond->_value == 1.0);
    CHECK(i->_alternative != nullptr);
    CHECK(i->_alternative->kind == NodeKind::Empty);
}

TEST_CASE("Parse IF-THEN-ELSE", "[parser]")
{
    auto prog = parseStr("SUB Main\nIF 1 THEN\nPRINT 1\nELSE\nPRINT 0\nEND IF\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto i = dynamic_cast<const If*>(seq._items[0].get());
    REQUIRE(i != nullptr);
    auto& thenBody = bodySeq(*i->_decision);
    CHECK(thenBody._items.size() == 1);
    auto& elseBody = bodySeq(*i->_alternative);
    CHECK(elseBody._items.size() == 1);
}

// ---- WHILE ----

TEST_CASE("Parse WHILE loop", "[parser]")
{
    auto prog = parseStr("SUB Main\nWHILE n <> 0\nPRINT n\nEND WHILE\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    auto w = dynamic_cast<const While*>(seq._items[0].get());
    REQUIRE(w != nullptr);
    auto cond = dynamic_cast<const Binary*>(w->_condition.get());
    REQUIRE(cond != nullptr);
    CHECK(cond->_operation == Operation::Ne);
}

// ---- FOR ----

TEST_CASE("Parse FOR loop", "[parser]")
{
    auto prog = parseStr("SUB Main\nFOR i = 1 TO 10\nPRINT i\nEND FOR\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    auto f = dynamic_cast<const For*>(seq._items[0].get());
    REQUIRE(f != nullptr);
    CHECK(f->_parameter->_name == "i");
    CHECK(f->_step->_value == 1.0);
}

TEST_CASE("Parse FOR with STEP", "[parser]")
{
    auto prog = parseStr("SUB Main\nFOR i = 1 TO 10 STEP 2\nPRINT i\nEND FOR\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto f = dynamic_cast<const For*>(seq._items[0].get());
    REQUIRE(f != nullptr);
    CHECK(f->_step->_value == 2.0);
}

TEST_CASE("Parse FOR with negative STEP", "[parser]")
{
    auto prog = parseStr("SUB Main\nFOR i = 10 TO 1 STEP -1\nPRINT i\nEND FOR\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto f = dynamic_cast<const For*>(seq._items[0].get());
    REQUIRE(f != nullptr);
    CHECK(f->_step->_value == -1.0);
}

// ---- CALL ----

TEST_CASE("Parse CALL with no arguments", "[parser]")
{
    auto prog = parseStr("SUB Main\nCALL foo\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    auto c = dynamic_cast<const Call*>(seq._items[0].get());
    REQUIRE(c != nullptr);
    CHECK(c->_subrCall->_callee == "foo");
    CHECK(c->_subrCall->_arguments.empty());
}

TEST_CASE("Parse CALL with arguments", "[parser]")
{
    auto prog = parseStr("SUB Main\nCALL foo 42, \"hi\"\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto c = dynamic_cast<const Call*>(seq._items[0].get());
    REQUIRE(c != nullptr);
    CHECK(c->_subrCall->_callee == "foo");
    REQUIRE(c->_subrCall->_arguments.size() == 2);
}

// ---- Expressions ----

TEST_CASE("Parse arithmetic expression", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = 1 + 2 * 3\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto b = dynamic_cast<const Binary*>(l->_expr.get());
    REQUIRE(b != nullptr);
    CHECK(b->_operation == Operation::Add);
    auto left = dynamic_cast<const Number*>(b->_left.get());
    REQUIRE(left != nullptr);
    CHECK(left->_value == 1.0);
    auto right = dynamic_cast<const Binary*>(b->_right.get());
    REQUIRE(right != nullptr);
    CHECK(right->_operation == Operation::Mul);
}

TEST_CASE("Parse comparison expression", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = 5 > 3\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto b = dynamic_cast<const Binary*>(l->_expr.get());
    REQUIRE(b != nullptr);
    CHECK(b->_operation == Operation::Gt);
}

TEST_CASE("Parse string concatenation", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = \"a\" & \"b\"\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto b = dynamic_cast<const Binary*>(l->_expr.get());
    REQUIRE(b != nullptr);
    CHECK(b->_operation == Operation::Conc);
}

TEST_CASE("Parse logical AND and OR", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = 1 AND 0 OR 1\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto orOp = dynamic_cast<const Binary*>(l->_expr.get());
    REQUIRE(orOp != nullptr);
    CHECK(orOp->_operation == Operation::Or);
    auto andOp = dynamic_cast<const Binary*>(orOp->_left.get());
    REQUIRE(andOp != nullptr);
    CHECK(andOp->_operation == Operation::And);
}

TEST_CASE("Parse unary minus", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = -5\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto u = dynamic_cast<const Unary*>(l->_expr.get());
    REQUIRE(u != nullptr);
    CHECK(u->_operation == Operation::Sub);
}

TEST_CASE("Parse unary NOT", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = NOT TRUE\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto u = dynamic_cast<const Unary*>(l->_expr.get());
    REQUIRE(u != nullptr);
    CHECK(u->_operation == Operation::Not);
}

TEST_CASE("Parse MOD operator", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = 10 MOD 3\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto b = dynamic_cast<const Binary*>(l->_expr.get());
    REQUIRE(b != nullptr);
    CHECK(b->_operation == Operation::Mod);
}

TEST_CASE("Parse TRUE and FALSE literals", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET a = TRUE\nLET b = FALSE\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 2);

    auto l1 = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l1 != nullptr);
    CHECK(dynamic_cast<const Boolean*>(l1->_expr.get()) != nullptr);
    CHECK(dynamic_cast<const Boolean*>(l1->_expr.get())->_value == true);

    auto l2 = dynamic_cast<const Let*>(seq._items[1].get());
    REQUIRE(l2 != nullptr);
    CHECK(dynamic_cast<const Boolean*>(l2->_expr.get()) != nullptr);
    CHECK(dynamic_cast<const Boolean*>(l2->_expr.get())->_value == false);
}

TEST_CASE("Parse parenthesized expression", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = (1 + 2) * 3\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto mul = dynamic_cast<const Binary*>(l->_expr.get());
    REQUIRE(mul != nullptr);
    CHECK(mul->_operation == Operation::Mul);
    auto add = dynamic_cast<const Binary*>(mul->_left.get());
    REQUIRE(add != nullptr);
    CHECK(add->_operation == Operation::Add);
}

TEST_CASE("Parse function call in expression", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = SIN(3.14)\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto a = dynamic_cast<const Apply*>(l->_expr.get());
    REQUIRE(a != nullptr);
    CHECK(a->_callee == "SIN");
    REQUIRE(a->_arguments.size() == 1);
}

TEST_CASE("Parse function call with multiple args", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = MID(\"hello\", 1, 2)\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto a = dynamic_cast<const Apply*>(l->_expr.get());
    REQUIRE(a != nullptr);
    CHECK(a->_callee == "MID");
    REQUIRE(a->_arguments.size() == 3);
}

TEST_CASE("Parse multiple statements", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = 1\nLET y = 2\nPRINT y\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 3);
    CHECK(dynamic_cast<const Let*>(seq._items[0].get()) != nullptr);
    CHECK(dynamic_cast<const Let*>(seq._items[1].get()) != nullptr);
    CHECK(dynamic_cast<const Print*>(seq._items[2].get()) != nullptr);
}

// ---- IF-ELSEIF ----

TEST_CASE("Parse IF with ELSEIF", "[parser]")
{
    auto prog = parseStr(
        "SUB Main\n"
        "IF x = 1 THEN\n"
        "  PRINT \"one\"\n"
        "ELSEIF x = 2 THEN\n"
        "  PRINT \"two\"\n"
        "ELSE\n"
        "  PRINT \"other\"\n"
        "END IF\n"
        "END SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);

    auto outer = dynamic_cast<const If*>(seq._items[0].get());
    REQUIRE(outer != nullptr);
    auto elseifNode = dynamic_cast<const If*>(outer->_alternative.get());
    REQUIRE(elseifNode != nullptr);
    CHECK(elseifNode->_condition != nullptr);
    CHECK(elseifNode->_alternative != nullptr);
    CHECK(elseifNode->_alternative->kind != NodeKind::Empty);
}

// ---- Error cases ----

TEST_CASE("Parse error: missing END SUB", "[parser]")
{
    auto prog = parseStr("SUB Main\nPRINT 1\n");
    CHECK(prog == nullptr);
}

TEST_CASE("Parse error: missing END IF", "[parser]")
{
    auto prog = parseStr("SUB Main\nIF 1 THEN\nPRINT 1\nEND SUB\n");
    CHECK(prog == nullptr);
}

TEST_CASE("Parse error: stray token", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = \nEND SUB\n");
    CHECK(prog == nullptr);
}

TEST_CASE("Parse error: IF without THEN", "[parser]")
{
    auto prog = parseStr("SUB Main\nIF 1\nPRINT 1\nEND IF\nEND SUB\n");
    CHECK(prog == nullptr);
}

// ---- Comments ----

TEST_CASE("Parse program with comments", "[parser]")
{
    auto prog = parseStr("' header\nSUB Main\n' body\nPRINT 1\n' footer\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    CHECK(sub._name == "Main");
    auto& seq = bodySeq(*sub._body);
    REQUIRE(seq._items.size() == 1);
    CHECK(dynamic_cast<const Print*>(seq._items[0].get()) != nullptr);
}

// ---- Power operator ----

TEST_CASE("Parse power operator is right-associative", "[parser]")
{
    auto prog = parseStr("SUB Main\nLET x = 2 ^ 3 ^ 2\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto l = dynamic_cast<const Let*>(seq._items[0].get());
    REQUIRE(l != nullptr);
    auto outer = dynamic_cast<const Binary*>(l->_expr.get());
    REQUIRE(outer != nullptr);
    CHECK(outer->_operation == Operation::Pow);
    CHECK(dynamic_cast<const Number*>(outer->_left.get()) != nullptr);
    auto inner = dynamic_cast<const Binary*>(outer->_right.get());
    REQUIRE(inner != nullptr);
    CHECK(inner->_operation == Operation::Pow);
}

// ---- Leading newlines ----

TEST_CASE("Parse program with leading newlines", "[parser]")
{
    auto prog = parseStr("\n\nSUB Main\nEND SUB\n");
    REQUIRE(prog != nullptr);
    REQUIRE(prog->_subroutines.size() == 1);
    CHECK(prog->_subroutines[0]->_name == "Main");
}

// ---- WHILE with comparison ----

TEST_CASE("Parse WHILE with EQ comparison", "[parser]")
{
    auto prog = parseStr("SUB Main\nWHILE x = 0\nPRINT x\nEND WHILE\nEND SUB\n");
    REQUIRE(prog != nullptr);
    auto& sub = onlySub(*prog);
    auto& seq = bodySeq(*sub._body);
    auto w = dynamic_cast<const While*>(seq._items[0].get());
    REQUIRE(w != nullptr);
    auto cond = dynamic_cast<const Binary*>(w->_condition.get());
    REQUIRE(cond != nullptr);
    CHECK(cond->_operation == Operation::Eq);
}
