// Generated by opencode with deepseek-v4-flash-free
#include "scanner.hxx"
#include "lexeme.hxx"

#include <catch2/catch_test_macros.hpp>

#include <sstream>

using namespace basic;

// Helper: scan one token from input string
struct ScanResult {
    Token kind;
    std::string value;
    unsigned line;
};

static ScanResult scanOne(std::string input) {
    auto stream = std::make_shared<std::istringstream>(std::move(input));
    Scanner scanner{*stream};
    auto lex = scanner.scan();
    return {lex.kind, lex.value, lex.line};
}

TEST_CASE("Scanner scans integer numbers", "[scanner]")
{
    auto r = scanOne("42");
    CHECK(r.kind == Token::Number);
    CHECK(r.value == "42");
    CHECK(r.line == 1);
}

TEST_CASE("Scanner scans multi-digit integer", "[scanner]")
{
    auto r = scanOne("100500");
    CHECK(r.kind == Token::Number);
    CHECK(r.value == "100500");
}

TEST_CASE("Scanner scans floating point numbers", "[scanner]")
{
    auto r = scanOne("3.14");
    CHECK(r.kind == Token::Number);
    CHECK(r.value == "3.14");
}

TEST_CASE("Scanner scans number starting with digit then dot", "[scanner]")
{
    auto r = scanOne("0.5");
    CHECK(r.kind == Token::Number);
    CHECK(r.value == "0.5");
}

TEST_CASE("Scanner scans text strings", "[scanner]")
{
    auto r = scanOne(R"("Hello, World!")");
    CHECK(r.kind == Token::Text);
    CHECK(r.value == "Hello, World!");
}

TEST_CASE("Scanner scans empty text string", "[scanner]")
{
    auto r = scanOne(R"("")");
    CHECK(r.kind == Token::Text);
    CHECK(r.value == "");
}

TEST_CASE("Scanner scans identifiers", "[scanner]")
{
    auto r = scanOne("myVar");
    CHECK(r.kind == Token::Identifier);
    CHECK(r.value == "myVar");
}

TEST_CASE("Scanner scans identifiers with digits", "[scanner]")
{
    auto r = scanOne("x42");
    CHECK(r.kind == Token::Identifier);
    CHECK(r.value == "x42");
}

TEST_CASE("Scanner recognizes all keywords", "[scanner]")
{
    auto check = [](std::string kw, Token expected) {
        auto r = scanOne(kw);
        INFO("Keyword: " << kw);
        CHECK(r.kind == expected);
    };

    check("SUB",    Token::Subroutine);
    check("LET",    Token::Let);
    check("PRINT",  Token::Print);
    check("INPUT",  Token::Input);
    check("IF",     Token::If);
    check("THEN",   Token::Then);
    check("ELSEIF", Token::ElseIf);
    check("ELSE",   Token::Else);
    check("WHILE",  Token::While);
    check("FOR",    Token::For);
    check("TO",     Token::To);
    check("STEP",   Token::Step);
    check("CALL",   Token::Call);
    check("END",    Token::End);
    check("MOD",    Token::Mod);
    check("AND",    Token::And);
    check("OR",     Token::Or);
    check("NOT",    Token::Not);
    check("TRUE",   Token::True);
    check("FALSE",  Token::False);
}

TEST_CASE("Identifier containing a keyword prefix is not a keyword", "[scanner]")
{
    auto r = scanOne("SUBTOTAL");
    CHECK(r.kind == Token::Identifier);
    CHECK(r.value == "SUBTOTAL");
}

TEST_CASE("Lowercase keyword is an identifier (case sensitive)", "[scanner]")
{
    auto r = scanOne("sub");
    CHECK(r.kind == Token::Identifier);
    CHECK(r.value == "sub");
}

TEST_CASE("Scanner scans single-char operators", "[scanner]")
{
    auto check = [](char ch, Token expected) {
        auto r = scanOne(std::string{ch});
        INFO("Operator: " << ch);
        CHECK(r.kind == expected);
    };

    check('+', Token::Add);
    check('-', Token::Sub);
    check('*', Token::Mul);
    check('/', Token::Div);
    check('^', Token::Pow);
    check('&', Token::Amp);
    check('=', Token::Eq);
    check('(', Token::LeftPar);
    check(')', Token::RightPar);
    check(',', Token::Comma);
}

TEST_CASE("Scanner scans multi-char comparison operators", "[scanner]")
{
    auto check = [](std::string input, Token expected, std::string expectedVal) {
        auto r = scanOne(input);
        INFO("Operator: " << input);
        CHECK(r.kind == expected);
        CHECK(r.value == expectedVal);
    };

    check("<",  Token::Lt, "<");
    check("<=", Token::Le, "<=");
    check("<>", Token::Ne, "<>");
    check(">",  Token::Gt, ">");
    check(">=", Token::Ge, ">=");
}

TEST_CASE("Scanner scans newlines", "[scanner]")
{
    auto r = scanOne("\n");
    CHECK(r.kind == Token::NewLine);
    CHECK(r.line == 1);
}

TEST_CASE("Scanner increments line number on newline", "[scanner]")
{
    std::istringstream input{"\n\n"};
    Scanner scanner{input};

    auto first = scanner.scan();
    CHECK(first.kind == Token::NewLine);
    CHECK(first.line == 1);

    auto second = scanner.scan();
    CHECK(second.kind == Token::NewLine);
    CHECK(second.line == 2);
}

TEST_CASE("Scanner skips comments", "[scanner]")
{
    std::istringstream input{"' this is a comment\n42"};
    Scanner scanner{input};

    auto nl = scanner.scan();
    CHECK(nl.kind == Token::NewLine);

    auto num = scanner.scan();
    CHECK(num.kind == Token::Number);
    CHECK(num.value == "42");
}

TEST_CASE("Scanner skips spaces between tokens", "[scanner]")
{
    std::istringstream input{"  42"};
    Scanner scanner{input};
    auto r = scanner.scan();
    CHECK(r.kind == Token::Number);
    CHECK(r.value == "42");
}

TEST_CASE("Scanner handles EOF after number", "[scanner]")
{
    std::istringstream input{"99"};
    Scanner scanner{input};
    scanner.scan();
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles empty input", "[scanner]")
{
    std::istringstream input{""};
    Scanner scanner{input};
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner scans a complete sequence of tokens", "[scanner]")
{
    std::istringstream input{"LET x = 42\nPRINT x"};
    Scanner scanner{input};

    auto t1 = scanner.scan();
    CHECK(t1.kind == Token::Let);
    CHECK(t1.value == "LET");

    auto t2 = scanner.scan();
    CHECK(t2.kind == Token::Identifier);
    CHECK(t2.value == "x");

    auto t3 = scanner.scan();
    CHECK(t3.kind == Token::Eq);

    auto t4 = scanner.scan();
    CHECK(t4.kind == Token::Number);
    CHECK(t4.value == "42");

    auto t5 = scanner.scan();
    CHECK(t5.kind == Token::NewLine);

    auto t6 = scanner.scan();
    CHECK(t6.kind == Token::Print);

    auto t7 = scanner.scan();
    CHECK(t7.kind == Token::Identifier);
    CHECK(t7.value == "x");

    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner scans a minimal BASIC program", "[scanner]")
{
    std::istringstream input{
        "SUB Main\n"
        "  PRINT \"Hello!\"\n"
        "END SUB\n"
    };
    Scanner scanner{input};

    CHECK(scanner.scan().kind == Token::Subroutine);

    auto mainId = scanner.scan();
    CHECK(mainId.kind == Token::Identifier);
    CHECK(mainId.value == "Main");

    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::Print);

    auto hello = scanner.scan();
    CHECK(hello.kind == Token::Text);
    CHECK(hello.value == "Hello!");

    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::End);
    CHECK(scanner.scan().kind == Token::Subroutine);
    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles IF-THEN with comparison", "[scanner]")
{
    std::istringstream input{"IF x <> 0 THEN"};
    Scanner scanner{input};

    CHECK(scanner.scan().kind == Token::If);
    CHECK(scanner.scan().kind == Token::Identifier);
    CHECK(scanner.scan().kind == Token::Ne);
    CHECK(scanner.scan().kind == Token::Number);
    CHECK(scanner.scan().kind == Token::Then);
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles FOR loop header", "[scanner]")
{
    std::istringstream input{"FOR i = 1 TO 10 STEP 2"};
    Scanner scanner{input};

    CHECK(scanner.scan().kind == Token::For);
    CHECK(scanner.scan().kind == Token::Identifier);

    auto eq = scanner.scan();
    CHECK(eq.kind == Token::Eq);

    auto one = scanner.scan();
    CHECK(one.kind == Token::Number);
    CHECK(one.value == "1");

    auto to = scanner.scan();
    CHECK(to.kind == Token::To);

    auto ten = scanner.scan();
    CHECK(ten.kind == Token::Number);
    CHECK(ten.value == "10");

    auto step = scanner.scan();
    CHECK(step.kind == Token::Step);

    auto two = scanner.scan();
    CHECK(two.kind == Token::Number);
    CHECK(two.value == "2");

    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles comparison chain", "[scanner]")
{
    std::istringstream input{"a <= b >= c"};
    Scanner scanner{input};

    CHECK(scanner.scan().kind == Token::Identifier);
    CHECK(scanner.scan().kind == Token::Le);
    CHECK(scanner.scan().kind == Token::Identifier);
    CHECK(scanner.scan().kind == Token::Ge);
    CHECK(scanner.scan().kind == Token::Identifier);
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles parentheses and commas", "[scanner]")
{
    std::istringstream input{"f(a, b)"};
    Scanner scanner{input};

    CHECK(scanner.scan().kind == Token::Identifier);
    CHECK(scanner.scan().kind == Token::LeftPar);
    CHECK(scanner.scan().kind == Token::Identifier);
    CHECK(scanner.scan().kind == Token::Comma);
    CHECK(scanner.scan().kind == Token::Identifier);
    CHECK(scanner.scan().kind == Token::RightPar);
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Consecutive comments are skipped", "[scanner]")
{
    std::istringstream input{"' comment 1\n' comment 2\n42"};
    Scanner scanner{input};

    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::NewLine);

    auto num = scanner.scan();
    CHECK(num.kind == Token::Number);
    CHECK(num.value == "42");
}

TEST_CASE("Text at EOF without closing quote", "[scanner]")
{
    auto r = scanOne(R"("unclosed)");
    CHECK(r.kind == Token::Text);
    CHECK(r.value == "unclosed");
}

TEST_CASE("Identifier ending at EOF", "[scanner]")
{
    std::istringstream input{"someLongIdentifier"};
    Scanner scanner{input};

    auto id = scanner.scan();
    CHECK(id.kind == Token::Identifier);
    CHECK(id.value == "someLongIdentifier");

    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Number at EOF", "[scanner]")
{
    std::istringstream input{"123"};
    Scanner scanner{input};

    auto num = scanner.scan();
    CHECK(num.kind == Token::Number);
    CHECK(num.value == "123");

    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Unknown symbol yields Token::None", "[scanner]")
{
    auto r = scanOne("@");
    CHECK(r.kind == Token::None);
    CHECK(r.value == "@");
}

TEST_CASE("Whitespace-only input yields EOF", "[scanner]")
{
    std::istringstream input{"   \t  "};
    Scanner scanner{input};
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles EOF immediately", "[scanner]")
{
    std::istringstream input{"\n"};
    Scanner scanner{input};
    auto nl = scanner.scan();
    CHECK(nl.kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles multiple newlines", "[scanner]")
{
    std::istringstream input{"\n\n\n"};
    Scanner scanner{input};
    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Comment at EOF", "[scanner]")
{
    std::istringstream input{"' just a comment"};
    Scanner scanner{input};
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Comment on last line before EOF", "[scanner]")
{
    std::istringstream input{"' line 1\n' line 2"};
    Scanner scanner{input};
    CHECK(scanner.scan().kind == Token::NewLine);
    CHECK(scanner.scan().kind == Token::Eof);
}

TEST_CASE("Scanner handles BASIC program with WHILE loop", "[scanner]")
{
    std::istringstream input{
        "SUB Main\n"
        "  INPUT n\n"
        "  WHILE n <> 0\n"
        "    PRINT n\n"
        "    LET n = n - 1\n"
        "  END WHILE\n"
        "END SUB\n"
    };
    Scanner scanner{input};

    auto sub = scanner.scan();
    CHECK(sub.kind == Token::Subroutine);

    auto name = scanner.scan();
    CHECK(name.kind == Token::Identifier);
    CHECK(name.value == "Main");
    CHECK(scanner.scan().kind == Token::NewLine);

    auto inp = scanner.scan();
    CHECK(inp.kind == Token::Input);

    auto ivar = scanner.scan();
    CHECK(ivar.kind == Token::Identifier);
    CHECK(ivar.value == "n");
    CHECK(scanner.scan().kind == Token::NewLine);

    auto wh = scanner.scan();
    CHECK(wh.kind == Token::While);

    auto wvar = scanner.scan();
    CHECK(wvar.kind == Token::Identifier);
    auto wne = scanner.scan();
    CHECK(wne.kind == Token::Ne);
    auto wzero = scanner.scan();
    CHECK(wzero.kind == Token::Number);
    CHECK(wzero.value == "0");
    CHECK(scanner.scan().kind == Token::NewLine);

    CHECK(scanner.scan().kind == Token::Print);

    auto pvar = scanner.scan();
    CHECK(pvar.kind == Token::Identifier);
    auto afterPrint = pvar.value;
    CHECK(scanner.scan().kind == Token::NewLine);

    auto let = scanner.scan();
    CHECK(let.kind == Token::Let);

    auto lvar = scanner.scan();
    CHECK(lvar.kind == Token::Identifier);
    auto leq = scanner.scan();
    CHECK(leq.kind == Token::Eq);
    auto lvar2 = scanner.scan();
    CHECK(lvar2.kind == Token::Identifier);
    auto lsub = scanner.scan();
    CHECK(lsub.kind == Token::Sub);
    auto lone = scanner.scan();
    CHECK(lone.kind == Token::Number);
    CHECK(lone.value == "1");
    CHECK(scanner.scan().kind == Token::NewLine);

    CHECK(scanner.scan().kind == Token::End);
    CHECK(scanner.scan().kind == Token::While);
    CHECK(scanner.scan().kind == Token::NewLine);

    CHECK(scanner.scan().kind == Token::End);
    CHECK(scanner.scan().kind == Token::Subroutine);
    CHECK(scanner.scan().kind == Token::NewLine);

    CHECK(scanner.scan().kind == Token::Eof);
}
